import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={""}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <Header />

            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
